services:
  eventdb:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PG_USERNAME:-linkkari}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-kissa123}
      POSTGRES_DB: ${PG_DATABASE:-eventdb}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  bot:
    build: .
    image: linkkibot:latest
    restart: on-failure
    env_file: .env
    environment:
      DATABASE_URL: postgres://${PG_USERNAME:-linkkari}:${PG_PASSWORD:-kissa123}@eventdb:5432/${PG_DATABASE:-eventdb}
    depends_on:
      eventdb:
        condition: service_healthy
        restart: true
    develop:
      watch:
        - action: rebuild
          path: src
    command: ["--modes", "month"]

volumes:
  db_data:
